version: '3.8'

services:
  postgres:
    container_name: agendaagil-postgresql
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=agendaagil
      - POSTGRES_PASSWORD=agendaagil
      - POSTGRES_DB=agendaagil_db   
    networks:
      - backend_network 
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}